Repository NLog/NLog.github.io, pull requests merged in 2019-11, with the labels that each got.

#135 NLog 4.6.8
  _config.yml
Labels: size/S

#134 Updated NLog.Extensions.AzureStorage packages
  config/targets.json
Labels: size/M

#136 Added external NLog.Targets.Http package
  config/targets.json
Labels: size/S

#137 Added more keywords
  config/targets.json
Labels: size/M, squash when passing
