Repository NLog/NLog.github.io, pull requests merged in 2022-04, with the labels that each got.

#186 Added blipboard.io target
  config/targets.json
Labels: size/XS

#183 Removed platforms when supporting all platforms
  config/layout-renderers.json
  config/layouts.json
  config/searchPage.js
  config/targets.json
Labels: size/XXL

#187 Aliases + cachebuster
  config/index.html
  config/item-type.js
  config/itemList.js
  config/layout-renderers.json
  config/searchPage.js
  config/targets.json
  config/targets.schema.json
  css/config.css
  css/config.less
Labels: size/L
