Repository NLog/NLog.github.io, pull requests merged in 2022-05, with the labels that each got.

#190 Updated NLog Homepage with extra features items
  index.html
Labels: size/M

#188 NLog 5.0 moves some layoutrenders into their own nuget-packages
  config/layout-renderers.json
  config/layouts.json
  config/targets.json
Labels: size/L

#181 NLog 5.0 Release Post
  _posts/2021-08-25-nlog-5-0-preview1-ready.md
  _posts/2022-05-16-nlog-5-0-finally-ready.md
Labels: size/M

#192 Custom 404 page with redirect
  404.md
Labels: size/S

#193 Update 404.md
  404.md
Labels: size/XS

#195 Update 2022-05-16-nlog-5-0-finally-ready.md (contributers)
  _posts/2022-05-16-nlog-5-0-finally-ready.md
Labels: size/XS

#196 NLog 5.0 Release Post now matches List of Major Changes
  _config.yml
  _posts/2022-05-16-nlog-5-0-finally-ready.md
Labels: size/M

#198 Added ToolStripItem-Target from NLog.Windows.Forms
  config/targets.json
Labels: size/S

#199 Fixed wiki link for RichTextBox-target
  config/targets.json
Labels: size/XS

#197 Add more features and another breaking change
  _posts/2021-08-25-nlog-5-0-preview1-ready.md
  _posts/2022-05-16-nlog-5-0-finally-ready.md
Labels: size/M

#200 Make it more explicit that it is Symbol type-name
  _posts/2021-08-25-nlog-5-0-preview1-ready.md
  _posts/2022-05-16-nlog-5-0-finally-ready.md
Labels: size/S

#201 Make it more explicit that it is type symbol-name
  _posts/2021-08-25-nlog-5-0-preview1-ready.md
  _posts/2022-05-16-nlog-5-0-finally-ready.md
Labels: size/XS

#202 Make it more explicit that it is type-alias
  _posts/2021-08-25-nlog-5-0-preview1-ready.md
  _posts/2022-05-16-nlog-5-0-finally-ready.md
Labels: size/S

#203 .NET Framework v4.0 platform replaced by .NET Framework v3.5
  _posts/2021-08-25-nlog-5-0-preview1-ready.md
  _posts/2022-05-16-nlog-5-0-finally-ready.md
Labels: size/XS

#191 NLog v5 XSD + nlog4.xsd
  schemas/NLog.xsd
  schemas/NLog4.xsd
Labels: size/XXL

#204 Update NLog.Targets.Syslog schema to version 7.0.0
  schemas/NLog.Targets.Syslog.xsd
Labels: size/L
