Repository NLog/NLog.github.io, pull requests merged in 2023-05, with the labels that each got.

#231 ADX as new NLog custom target
  config/targets.json
Labels: size/XS

#230 NLog 5.2 Release Post
  _posts/2022-05-16-nlog-5-0-finally-ready.md
  _posts/2023-05-30-nlog-5-2-trim-warnings.md
Labels: size/L

#232 NLog 5.2 Release Post (fix utf8)
  _posts/2023-05-30-nlog-5-2-trim-warnings.md
Labels: size/XS

#233 NLog 5.2 Release Post (add headline)
  _posts/2023-05-30-nlog-5-2-trim-warnings.md
Labels: size/XS

#234 NLog 5.2 Release Post (fix sentences)
  _posts/2023-05-30-nlog-5-2-trim-warnings.md
Labels: size/S
