Repository NLog/NLog.github.io, pull requests merged in 2023-08, with the labels that each got.

#242 adding kafka target
  config/targets.json
Labels: size/S

#243 Removed keywords and wrapper since not improving
  config/layout-renderers.json
  config/targets.json
Labels: size/XL

#244 Network-target supports TCP / UDP / SSL / TLS
  config/targets.json
Labels: size/XS

#245 Added NLog.Targets.InfluxDB
  config/targets.json
Labels: size/S

#247 Updated NLog v5 release-post to say major breaking changes
  _posts/2022-05-16-nlog-5-0-finally-ready.md
Labels: size/XS
